"""
Django settings for imprest_portal project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os, random, string
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Environment mode
ENVIRONMENT = config('DJANGO_ENV', default='development')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="".join(random.choices(string.printable, k=64)))


# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG setting based on environment
DEBUG = ENVIRONMENT == 'development'


# ALLOWED_HOSTS based on environment
ALLOWED_HOSTS = ['*'] if DEBUG else str(config('ALLOWED_HOSTS', default='localhost')).split(',')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'drf_spectacular',
    'rest_framework',

    # Local apps
    'users.apps.UsersConfig',
    'roles.apps.RolesConfig',
    'stores.apps.StoresConfig',
    'purchases.apps.PurchasesConfig',
    'helpers.apps.HelpersConfig',
]

AUTH_USER_MODEL = 'users.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'imprest_portal.urls'



AZURE_AD_AUTHORITY = f"https://login.microsoftonline.com/{config('AZURE_AD_TENANT_ID', default='no id')}"
AZURE_AD_REDIRECT_URI = config('AZURE_AD_REDIRECT_URI', default='no uri set')
AZURE_AD_TENANT_ID = config('AZURE_AD_TENANT_ID', default='no id')
AZURE_AD_CLIENT_ID = config('AZURE_AD_CLIENT_ID', default='no id')
AZURE_AD_CLIENT_SECRET = config('AZURE_AD_CLIENT_SECRET', default='no id')

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


FRONTEND_URL = config('FRONTEND_URL', default='FRONTEND_URL') 
AZURE_AD_LOGOUT_URL = f"{AZURE_AD_AUTHORITY}/oauth2/v2.0/logout?post_logout_redirect_uri={FRONTEND_URL}"


# CORS settings based on environment
# if DEBUG:
CORS_ALLOW_ALL_ORIGINS = True
# else:
#     CORS_ALLOWED_ORIGINS = [
#         "https://172.16.0.95",
#         "https://calloverapp.wajesmarthrms.website",
#     ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'imprest_portal.wsgi.application'

DB_ENGINE = config('DB_ENGINE', default='postgresql')
USE_SSL = config('DB_USE_SSL', default='False', cast=bool)

# Database configuration

DB_ENGINE = config('DB_ENGINE', default='postgresql')
USE_SSL = config('DB_USE_SSL', default='False', cast=bool)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.' + DB_ENGINE,
        'NAME': config('DB_NAME', default='imprest_dev'),
        'USER': config('DB_USER', default='your_db_user'),
        'PASSWORD': config('DB_PASSWORD', default='your_db_password'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432' if DB_ENGINE == 'postgresql' else '3306'),
        'OPTIONS': {
            'sslmode': 'require'
        } if DB_ENGINE == 'postgresql' and USE_SSL else {},
    }
}


if ENVIRONMENT == 'production':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.mssql',
        'NAME': config('DB_NAME', default='prod_database'),
        'USER': config('DB_USER', default='prod_user'),
        'PASSWORD': config('DB_PASSWORD', default='prod_password'),
        'HOST': config('DB_HOST', default='prod_server'),
        'PORT': config('DB_PORT', default='1433'),
        'OPTIONS': {'driver': 'ODBC Driver 17 for SQL Server'},
    }

    
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=120),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

#REST_FRAMEWORK SETTINGS
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',  # Enforce JSON-only responses
    ),
    'EXCEPTION_HANDLER': 'helpers.error_handler.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

#Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='your_host_user')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='your_app_password')# Use an App Password, not your real password
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

SPECTACULAR_SETTINGS = {
    'TITLE': 'IMPREST PORTAL API DOCUMENTATION',
    'DESCRIPTION': 'Your API Description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # Other optional settings here
}
